### ISSUE TITLE
Increase contrast on links that aren't headings

### ISSUE THREAD

**Issue by seanredmond** [nypl-spacetime/nypl-spacetime.github.io#15]
The visited link color combination (#599b36/#f7f7f7) is too low (3.2) for text that isn't large (18pt) or 14pt and bold. The base link color has an even lower ratio (2.1)

**Comment by wlla** [comment]
Updated all $linkcolor to $nypldarkgreen (#437529) to resolve this. New base color combination (#437529/#f7f7f7) is 5.5 and color combination (#2d4f1c/#f7f7f7) for visted links is 9.3.
