### ISSUE TITLE
Adjacent links to the same CC URL

### ISSUE THREAD

**Issue by seanredmond** [nypl-spacetime/nypl-spacetime.github.io#8]
At the bottom of the page there are two links two CC links, "Creative Commons CC0 1.0 Universal Public Domain" and "Creative Commons CC0 1.0 Universal Public Domain Dedication" that both go to  https://creativecommons.org/publicdomain/zero/1.0/. This creates a lot of redundancy for screen readers and, apart from that, I can't really divine the difference between the designation and the dedication. Should be rewritten so that there is only one link.

**Comment by wlla** [comment]
Updated Footer language. We can now use the following footers:   

The data produced through this project is covered by a [Creative Commons CC0 1.0 Universal Public Domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication. By participating in this project, you agree that any copyrightable content you submit shall be subject this Creative Commons CC0 1.0 Universal Public Domain dedication.
